root@udibaraid:/home/udibaraid/Project/Tugas1/proyek-pertama# docker compose up
[+] Running 2/2
 ✔ Container proyek-pertama-item-db-1   Recreated                          0.5s 
 ✔ Container proyek-pertama-item-app-1  Recreated                          0.5s 
Attaching to proyek-pertama-item-app-1, proyek-pertama-item-db-1
proyek-pertama-item-db-1   | 2023-12-09T17:41:39.729+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=76a2a59d12ab
proyek-pertama-item-db-1   | 2023-12-09T17:41:39.729+0000 I CONTROL  [initandlisten] db version v3.6.23
proyek-pertama-item-db-1   | 2023-12-09T17:41:39.729+0000 I CONTROL  [initandlisten] git version: d352e6a4764659e0d0350ce77279de3c1f243e5c
proyek-pertama-item-db-1   | 2023-12-09T17:41:39.729+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
proyek-pertama-item-db-1   | 2023-12-09T17:41:39.729+0000 I CONTROL  [initandlisten] allocator: tcmalloc
proyek-pertama-item-db-1   | 2023-12-09T17:41:39.729+0000 I CONTROL  [initandlisten] modules: none
proyek-pertama-item-db-1   | 2023-12-09T17:41:39.729+0000 I CONTROL  [initandlisten] build environment:
proyek-pertama-item-db-1   | 2023-12-09T17:41:39.729+0000 I CONTROL  [initandlisten]     distmod: ubuntu1604
proyek-pertama-item-db-1   | 2023-12-09T17:41:39.729+0000 I CONTROL  [initandlisten]     distarch: x86_64
proyek-pertama-item-db-1   | 2023-12-09T17:41:39.729+0000 I CONTROL  [initandlisten]     target_arch: x86_64
proyek-pertama-item-db-1   | 2023-12-09T17:41:39.729+0000 I CONTROL  [initandlisten] options: { net: { bindIpAll: true } }
proyek-pertama-item-db-1   | 2023-12-09T17:41:39.730+0000 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
proyek-pertama-item-db-1   | 2023-12-09T17:41:39.730+0000 I STORAGE  [initandlisten] 
proyek-pertama-item-db-1   | 2023-12-09T17:41:39.730+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
proyek-pertama-item-db-1   | 2023-12-09T17:41:39.730+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
proyek-pertama-item-db-1   | 2023-12-09T17:41:39.730+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=1386M,cache_overflow=(file_max=0M),session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),compatibility=(release="3.0",require_max="3.0"),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
proyek-pertama-item-app-1  | 
proyek-pertama-item-app-1  | > docker-software-delivery@1.0.0 start /app
proyek-pertama-item-app-1  | > node ./bin/www
proyek-pertama-item-app-1  | 
proyek-pertama-item-app-1  | NODE_ENV: production
proyek-pertama-item-db-1   | 2023-12-09T17:41:40.721+0000 I STORAGE  [initandlisten] WiredTiger message [1702143700:720383][1:0x7f16456b1a40], txn-recover: Main recovery loop: starting at 1/32384
proyek-pertama-item-app-1  | /app/node_modules/mongodb/lib/mongo_client.js:421
proyek-pertama-item-app-1  |           throw err
proyek-pertama-item-app-1  |           ^
proyek-pertama-item-app-1  | 
proyek-pertama-item-app-1  | AssertionError [ERR_ASSERTION]: null == Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 172.18.0.2:27017
proyek-pertama-item-app-1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
proyek-pertama-item-app-1  |   name: 'MongoError'
proyek-pertama-item-app-1  | }]
proyek-pertama-item-app-1  |     at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
proyek-pertama-item-app-1  |     at Pool.emit (events.js:400:28)
proyek-pertama-item-app-1  |     at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
proyek-pertama-item-app-1  |     at Object.onceWrapper (events.js:520:26)
proyek-pertama-item-app-1  |     at Connection.emit (e...
proyek-pertama-item-app-1  |     at /app/app.js:24:10
proyek-pertama-item-app-1  |     at connectCallback (/app/node_modules/mongodb/lib/mongo_client.js:527:5)
proyek-pertama-item-app-1  |     at /app/node_modules/mongodb/lib/mongo_client.js:418:11
proyek-pertama-item-app-1  |     at processTicksAndRejections (internal/process/task_queues.js:77:11) {
proyek-pertama-item-app-1  |   generatedMessage: true,
proyek-pertama-item-app-1  |   code: 'ERR_ASSERTION',
proyek-pertama-item-app-1  |   actual: null,
proyek-pertama-item-app-1  |   expected: Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 172.18.0.2:27017
proyek-pertama-item-app-1  |       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
proyek-pertama-item-app-1  |     name: 'MongoError'
proyek-pertama-item-app-1  |   }]
proyek-pertama-item-app-1  |       at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
proyek-pertama-item-app-1  |       at Pool.emit (events.js:400:28)
proyek-pertama-item-app-1  |       at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
proyek-pertama-item-app-1  |       at Object.onceWrapper (events.js:520:26)
proyek-pertama-item-app-1  |       at Connection.emit (events.js:400:28)
proyek-pertama-item-app-1  |       at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:189:49)
proyek-pertama-item-app-1  |       at Object.onceWrapper (events.js:520:26)
proyek-pertama-item-app-1  |       at Socket.emit (events.js:400:28)
proyek-pertama-item-app-1  |       at emitErrorNT (internal/streams/destroy.js:106:8)
proyek-pertama-item-app-1  |       at emitErrorCloseNT (internal/streams/destroy.js:74:3),
proyek-pertama-item-app-1  |   operator: '=='
proyek-pertama-item-app-1  | }
proyek-pertama-item-app-1  | npm ERR! code ELIFECYCLE
proyek-pertama-item-app-1  | npm ERR! errno 1
proyek-pertama-item-app-1  | npm ERR! docker-software-delivery@1.0.0 start: `node ./bin/www`
proyek-pertama-item-app-1  | npm ERR! Exit status 1
proyek-pertama-item-app-1  | npm ERR! 
proyek-pertama-item-app-1  | npm ERR! Failed at the docker-software-delivery@1.0.0 start script.
proyek-pertama-item-app-1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
proyek-pertama-item-app-1  | 
proyek-pertama-item-app-1  | npm ERR! A complete log of this run can be found in:
proyek-pertama-item-app-1  | npm ERR!     /root/.npm/_logs/2023-12-09T17_41_40_833Z-debug.log
proyek-pertama-item-db-1   | 2023-12-09T17:41:40.853+0000 I STORAGE  [initandlisten] WiredTiger message [1702143700:853838][1:0x7f16456b1a40], txn-recover: Recovering log 1 through 2
proyek-pertama-item-db-1   | 2023-12-09T17:41:40.922+0000 I STORAGE  [initandlisten] WiredTiger message [1702143700:922930][1:0x7f16456b1a40], txn-recover: Recovering log 2 through 2
proyek-pertama-item-db-1   | 2023-12-09T17:41:40.974+0000 I STORAGE  [initandlisten] WiredTiger message [1702143700:974915][1:0x7f16456b1a40], txn-recover: Set global recovery timestamp: 0
proyek-pertama-item-db-1   | 2023-12-09T17:41:41.028+0000 I CONTROL  [initandlisten] 
proyek-pertama-item-db-1   | 2023-12-09T17:41:41.028+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
proyek-pertama-item-db-1   | 2023-12-09T17:41:41.028+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
proyek-pertama-item-db-1   | 2023-12-09T17:41:41.028+0000 I CONTROL  [initandlisten] 
proyek-pertama-item-db-1   | 2023-12-09T17:41:41.029+0000 I CONTROL  [initandlisten] 
proyek-pertama-item-db-1   | 2023-12-09T17:41:41.029+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
proyek-pertama-item-db-1   | 2023-12-09T17:41:41.029+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
proyek-pertama-item-db-1   | 2023-12-09T17:41:41.029+0000 I CONTROL  [initandlisten] 
proyek-pertama-item-db-1   | 2023-12-09T17:41:41.037+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
proyek-pertama-item-db-1   | 2023-12-09T17:41:41.037+0000 I NETWORK  [initandlisten] listening via socket bound to 0.0.0.0
proyek-pertama-item-db-1   | 2023-12-09T17:41:41.037+0000 I NETWORK  [initandlisten] listening via socket bound to /tmp/mongodb-27017.sock
proyek-pertama-item-db-1   | 2023-12-09T17:41:41.037+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
proyek-pertama-item-app-1 exited with code 0
proyek-pertama-item-app-1  | 
proyek-pertama-item-app-1  | > docker-software-delivery@1.0.0 start /app
proyek-pertama-item-app-1  | > node ./bin/www
proyek-pertama-item-app-1  | 
proyek-pertama-item-app-1  | NODE_ENV: production
proyek-pertama-item-db-1   | 2023-12-09T17:41:42.112+0000 I NETWORK  [listener] connection accepted from 172.18.0.3:43464 #1 (1 connection now open)
proyek-pertama-item-db-1   | 2023-12-09T17:41:42.119+0000 I NETWORK  [conn1] received client metadata from 172.18.0.3:43464 conn1: { driver: { name: "nodejs", version: "2.2.36" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "6.1.0-14-amd64" }, platform: "Node.js v14.21.3, LE, mongodb-core: 2.1.20" }
proyek-pertama-item-app-1  | Connected to database
